#copyright: Copyright &copy; 2020-2025
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: "blob/develop/docs/src/"
repo_url: https://github.com/saxix/django-adminactions
site_dir: ./~build/docs
site_name: django-adminactions
site_url: https://github.com/saxix/django-adminactions
strict: false
exclude_docs: |
    _docs/*
    _hooks/*
    _includes/*
    _scripts/*
    ~*

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    -   pymdownx.tasklist:
            custom_checkbox: true
            clickable_checkbox: true
    -   pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
    -   pymdownx.highlight:
            anchor_linenums: true
            line_spans: __span
            pygments_lang_class: true
    - pymdownx.inlinehilite
#  - pymdownx.magiclink
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
#
theme:
    name: "material"
#    color_mode: auto

    #  custom_dir: docs/_theme/overrides
    #  favicon: img/favicon.ico
    #  logo: img/logo.png
    highlightjs: true
    hljs_languages:
        - yaml
        - django
#    user_color_mode_toggle: true
    palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        accent: indigo

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        #    - content.action.edit
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - header.autohidex
        #    - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
#  extra:
#    version:
#      provider: mike
#      alias: true

plugins:
    - awesome-pages
    - include-markdown
    - git-authors
    - glightbox
    - tags
    - markdownextradata
    -   ezlinks:
            wikilinks: true
    -   mkdocstrings:
            default_handler: python
            handlers:
                python:
                    show_docstring_attributes: true
                    inventories:
                        - https://installer.readthedocs.io/en/stable/objects.inv
                        - https://django.readthedocs.org/en/5.1.x/objects.inv
                        #            - url: https://docs.python.org/3.13/objects.inv
                        #              domains: [std, py, csv]
                        - https://docs.python.org/3.13/objects.inv

    - search
#  - gen-files:
#      scripts:
#        - docs/_scripts/get_settings.py
watch:
    - src/
hooks:
    - docs/_hooks/hooks.py
    - docs/_hooks/sax.py
    - docs/_hooks/shortcodes.py

extra:
    interwiki:
        github: https://github.com/saxix/django-adminactions/issues/
        stackoverflow: stackoverflow.com/questions/
        google: https://www.google.com/search?q=
