[tox]
requires =
    tox>=4.2
    tox-uv>=1.20.2
env_list =
    lint
    docs
    pkg_meta
    d{51, 42, 32}-py{313, 312, 311, 310}

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    celery
    d32: django==3.2.*
    d42: django==4.2.*
    d51: django==5.1.*
pass_env =
    CELERY_BROKER_URL
    DISPLAY
set_env =
    CELERY_ALWAYS_EAGER = 1
    COVERAGE_FILE = {env:COVERAGE_FILE:{toxworkdir}{/}.coverage-{envname}}
    CRYPTOGRAPHY_DONT_BUILD_RUST = 1
    DATABASE_URL = sqlite:///adminactions.sqlite
    PYTHONDONTWRITEBYTECODE = true
    PYTHONPATH = ./src:./tests
commands =
    coverage erase
    coverage run -m pytest --selenium-enable --junitxml {toxworkdir}{/}coverage-{envname}.xml {posargs:tests}
    coverage combine
    coverage report
    coverage html -d {envtmpdir}{/}htmlcov
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
skip_install = true
commands =
    mkdocs build -d ./docs/output
dependency_groups = docs

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir}

[testenv:type]
description = run type check on code base
deps =
    mypy==1.11.2
commands =
    mypy --strict src
    mypy --strict tests

[testenv:runserver]
description = run type check on code base
deps =
    django==5.1.*
set_env =
    CELERY_ALWAYS_EAGER = 1
    CRYPTOGRAPHY_DONT_BUILD_RUST = 1
    DATABASE_URL = sqlite:///adminactions.sqlite
    DJANGO_SETTINGS_MODULE = demo.settings
    PYTHONDONTWRITEBYTECODE = true
    PYTHONPATH = ./src:./tests
commands =
    django-admin migrate
    django-admin runserver

[gh-actions]
python =
    3.13: py313, pkg_meta
    3.12: py312
    3.11: py311
    3.10: py310

[gh-actions:env]
django =
    5.1: d51
    4.2: d42
    3.2: d32
