[tox]
requires =
    tox>=4.2
    tox-uv>=1.20.2
env_list =
    lint
    docs
    package
    d{50, 42, 32}-py{313, 312, 311}

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d50: django==5.0.*
    pypy: psycopg2cffi
pass_env =
    CELERY_BROKER_URL
    DISPLAY
set_env =
    CELERY_ALWAYS_EAGER = 1
    CRYPTOGRAPHY_DONT_BUILD_RUST = 1
    DATABASE_URL = postgres://postgres:postgres@127.0.0.1:5432/adminactions
    PYTHONDONTWRITEBYTECODE = true
    PYTHONPATH = ./src:./tests
commands =
    {posargs:pytest tests/ src --doctest-modules --create-db}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using flake8
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure
