AA_PERMISSION_CREATE_USE_SIGNAL = 1
AA_PERMISSION_CREATE_USE_APPCONFIG = 2
AA_PERMISSION_CREATE_USE_COMMAND = 3
AA_PERMISSION_HANDLER_VALUES = [
    AA_PERMISSION_CREATE_USE_SIGNAL,
    AA_PERMISSION_CREATE_USE_APPCONFIG,
    AA_PERMISSION_CREATE_USE_COMMAND,
]
